
services:
  worknetdb:
    container_name: worknet-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8003:1433
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=admin@123
    networks:
      - worknet-network

  worknetapi:
    container_name: worknet-api
    image: mzziin/worknetapi:latest
    build:
      context: .
      dockerfile: WorkNetAPI/Dockerfile
    ports:
      - 8001:8080
      - 8002:8081
    depends_on:
      - worknetdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=worknetDb
      - DB_NAME=WorkNetDb
      - DB_SA_PASSWORD=admin@123
    networks:
      - worknet-network

networks:
  worknet-network:

volumes:
    sqlvolume:
